project:
  type: website
  output-dir: docs

website:
  title: "Blog: Elías José Mantilla Ibarra"
  sidebar: 
    style: "docked"
    search: true
    logo: "./assets/logo.jpg"
    contents: 
      - section: "Personal Statement"
        contents: 
          - index.qmd
          - about.qmd
          - economics.qmd
      - section: "EDA and Visualization"
        contents:
          - procyclicality.qmd
      - section: "Statistics"
      - section: "Machine Learning"
      - section: "Deep Learning"
      - section: "Deployment and Integration"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



