project:
  type: website
  output-dir: docs
  
  preview: 
    port: 5555
    browser: true
    watch-inputs: true
    navigate: true
  
  render: 
    - "*.qmd"
    
  resources: 
    - "assets/"
    
freeze: true
    
# Metadata
pagetitle: "{{< meta title >}} | Elías Mantilla"
description-meta: "Elías Mantilla: A personal and professional site"
author-meta: "Elías Mantilla"

website:
  title: "Elías José Mantilla Ibarra"
  description: "{{< meta description-meta >}}"
  favicon: /assets/favicon.ico
  
  
  navbar: 
    pinned: True
    
    left: 
      - text: "About"
        href: "index.qmd"
      - text: "CV"
        href: "cv/index.qmd"
      - text: "Portfolio"
        href: "portfolio/index.qmd"
      - text: "Blog"
        file: "blog/index.qmd"
        
    right: 
      - icon: twitter
        aria-label: twitter
        href: https://twitter.com/ejmantilla
        rel: me
      - icon: github
        aria-label: github
        href: https://github.com/ekmanib
        rel: me
      - icon: linkedin
        aria-label: linkedin
        href: https://www.linkedin.com/in/emantilla2000
        rel: me

format:
  html:
    theme: 
      - html\style.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    highlight-style: monokai

