project:
  type: website
  output-dir: docs

website:
  title: "Blog: Elías José Mantilla Ibarra"
  sidebar: 
    style: "docked"
    search: true
    logo: "./assets/logo.jpg"
    contents: 
      - section: "Personal Statement"
        contents: 
          - index.qmd
          - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



