---
title: "Curriculum Vitae"
subtitle: "Elías José Mantilla Ibarra"
toc: false
---

## Overview
Economist with Honors (Cum Laude) by the University San Francisco de Quito, Ecuador. During my undergraduate studies I explored a wide variety of advanced classes such as Complexity Economics - where I learned about network data analysis and agent-based modelling. I did a semester of international exchange in Chile (2021) where I farther delved into advanced topics such as economic history and undertook practical work replicating papers in macroeconomics. Additionally, I have experience chiefly as research assistant:

* Wrangling and prepping data for analysis with Pandas (Python)
* Exploratory data analysis via statistical summaries and data visualization (Python and R)
* NHST (Null Hypothesis Significance Testing - Python and R). In the frequentist tradition.

Currently working on acquiring the following skills:

* Expand my knowledge on Bayesian Statistics, Comparing Models, Multilevel Models. Reading the fascinating book "Statistical Rethinking" by Richard McElreath.
* Machine learning and deep learning
* Spatial and network data analysis
* Software Engineering.

## Experience
### Research Assistant at Computational Social Sciences Laboratory USFQ
#### Quito, Ecuador (2021, Jan - 2022, Jul)
I work as research assistant for the Data Hub, a project of the Computational Social Science Lab from Universidad San Francisco de Quito. My experience include collecting data, analyzing and visualizing it, and writing short reports as well as presentations. Tools I often use are Python and R.

### Junior Consultant
#### Quito, Ecuador (2021, Jun - 2021, Ago)
As part of a team of four, we conducted the analysis and classification of investment project and other funding from various sources, both public and private, that are flowing to meet the demands of each of the 17 Sustainable Development Goals by the UN. I mainly working with Python to scrape online data.

## Education
### Summer School in Economic Networks - Oxford University
I attended the Oxford Summer School in Economic Networks. There I learned about the cutting edge research on the field of network science, particularly applied to social phenomena. I now feel confident working with the statistical methods required to analyze network data.

### Bacherlor's in Economic - Universidad San Francisco de Quito
Economist (2019-2022)

### International Student - Pontificia Universidad Católica de Chile
International Student (2021)