---
title: Why Economics?
subtitle: A Literacy Narrative From My Sophomore Year In College
toc: false
---

A social scientist studies the mechanisms of human interactions. They attempt to bring about relevant ideas, classify and organize the knowledge concerning human society. Their explanations differ from those evolutionary and biological, in that they are concerned not only with raw observations of human habitats but with the collective imagination that permeate those habitats. The social scientist intends to understand the conceptualized representations of an individual within the society, as well to observe the macro-movements.

The importance of the social scientist stems from the need to comprehend the underlying reasons for our actions. As an economics student, I must, to a large extend, obey this logic. I am now in the middle of my quest to become a good social scientist, to be useful for society and to contribute to the body of works underpinning our understanding of social systems and of ourselves. I am still trying to form coherent ideas about myself and the world at a slow but relentless pace.

The idea to be in the social sciences once I had to go to college first began to appear to me as I was learning languages during my spare in high school. By the time I graduated high school, I could confidently hold a conversation in Spanish, English, French and German and slight less in Italian and Dutch. This was because over three years before I had committed myself to becoming a polyglot. In the process, I learned the different ways the languages differ from each other, their similarities and some specificities that unveil nuggets of culture and history.

European history became the source for my daily enthusiasm, particularly wars. I discussed with friends and teachers everything I read and watched on Napoleonic wars, World Wars and the Cold War. Thus, I began to notice how much I enjoyed, not only consuming contents in foreign languages, but the many aspects of human life that were involved in those events; a series of angles ranging from politics, economics, sociology to psychology.

At the same time, and with purpose to improve in the languages, I began to watch politicians speak. I fantasized about working at the UN, or at an NGO. So I approached people who could offer me the opportunity to participate in events, ‘modelos’, where I could hone debating skills. I had to talk to a Frenchman at the EU delegation. This is because I can’t remember a single time when my school was invited.

Since the ‘modelo’ was for the European Union, I had to prepare for a debate around topics concerning the EU. As I researched information, I read a lot about economic crisis. This was 2013, and southern European countries were having a tough time. At the end of event, I was more than convinced that economics is my thing, over diplomacy or international relations. Probably, I became subconsciously attracted to the problems that economics deals with. While researching, I came across the terms interest rates, eurozone and debt crisis. My mind now turned its attention to questions such as: What is Banking and how it works? What determined the value of a currency vis-à-vis another, foreign currency?

At the time, I couldn’t fully articulate those questions, but the idea that economics was the field that I wanted to spend time studying, would remain unchanged.

It’s been two full semesters already of having enrolled in the economics program. There are great things about economics, and not so great things about economics. For instance, I admire my professor, who are people committing their life to do research on intriguing and interesting questions that concern the future of our institutions, our understanding of development and State building. Yet there have been times to dispel the misconceptions I had about economics. For example, I didn’t know about mathematical modeling and the uses of specific models. I thought that mathematics was only used in the form of Statistics to analyze data, but, as it turns out, it is used to formulate theory.

Although I do not oppose the use of mathematics in economics, quite on the contrary, I support rigorous methods, some of the assumptions made to build up those models are very problematic. So, I finally understood why economics is much criticized. One set of these assumptions are the axioms of rationality. These axioms assure the modeler that an individual, or agent in economic jargon, always has an ordered set of preferences and that this individual, or agent, is going to act as if maximizing his or her pleasure exhausting his or her available resources. This is part of the neoclassical school of economics, and the ideas it advocated would sweep the world.

According to Neoclassical models, the uninterrupted, disaggregated marketplace for the exchange of goods and services produce the most efficient outcome. This led to believe that any alternative other than the free market is to be ignored because of the ultimate superiority of the capitalist free market. This to me, and many others, sound more like an ideology than a logical conclusion from observed phenomena and reasoned theory.

Unfortunately, economics has fallen prey to many ideologues, in the present as it has been throughout history. Even still, I love the field. Yet, as a social scientist I need to recognize the pitfalls of becoming enthralled by the conventional wisdom and stop asking questions. As a good social scientist, an aim that I pursue, I shall not let one representation of the world get in the way of my curiosity.

In accordance with my idealization of the good social scientist, I shall work toward rendering economics its due importance, by making it useful. This may require reconsidering methodologies, stepping back from preconceived ideas, challenging past assumptions and meeting with people. All that to further advance the process in understanding of human interaction and commerce and propose solutions to the most pressive problems that economics has promised to solve.
