---
title: "Personal Statement"
subtitle: "Elías José Mantilla Ibarra"
---

A meaningful life is one devoted to a purpose larger than one's life. This ultimate goal should serve to guide our decisions at both easy and hard times. Although it may seem a difficult choice, I have simplified and rather considered simple, but extremely meaningful, rules of thumb to live and lead by. This rules consist of values I must always uphold, no matter the consequences. They should guide my decisions both in private and intimate settings as well as public and professional.

There are two main values. Under any circumstance I want to remain true to the values of Honesty and Curiosity. One may argue that either one of those is not exactly a virtue, but I'd argue in favor of considering them as such. Honesty entails a commitment to truth while Curiosity entails a commitment to, and appreciation of, the path to knowledge. In order not to be misled, I add the value of Compassion, so as to ensure that I will act in good faith and from a place of love. As life is uncertain and all paths forward intricate, I remain confident in that being responsible in upholding those values will get me somewhere I would want to be.

This has practical implications for my career path. A non exhaustive list would include: I'll always foster open and transparent environments, no or very little politics; I'll seek growth over comfort; I'll seek autonomy; I'll act in good faith and will demand the same in return, although it cannot be expected. That is as far as I can foresee. My values are firm.

This does not only mean that I will prefer some environment over other. There are strong consequences regarding my attitudes and daily choices. For instance, in order to deserve a job whose allure has captivated my attention I must put in honest and hard work towards becoming the kind of person that would be suited for the job. It must be the case that I will exhibit the kind of work ethic, in combination with the cunning and intelligence, to learn, create and network my way to the job.

As of the time of this writing (20-07-2023), I am an aspiring data scientist. Grosso modo, I'm on the right track but still lack the necessary skills to realistically compete for jobs. 

The times ahead present challenging and joyful days. I'm entirely responsible to fill my days with energy and work, always uplifted by the fact that I am diligent in respecting this commitment that I make to myself. Consistently living up to these rules will imbue my life with meaning and purpose. Otherwise, I will suffer grave consequences. Beyond these rules I do have more specific, material goals that should never distract me from respecting and upholding my values. I must be patient. I must work hard. I must take pride in my good choices. I must not let ambition for quick gains blindfold me. I must aspire the good life.


